<html>
  <head>
  <title>input Data Registrasi</title>
</head>
<body>
  <form action="tampilandataregistrasi.php"method="post">
    <b>Form Registrasi</b>
    <br>
    <pre>
      Nama: <input type="text" name="nama" size="25"maxlength="50">
      Alamat: <input type="text" name="alamat" size="25"maxlength="50">
      Tempat_lahir: <input type="text" name="tempatlahir" size="25"maxlength="50">
      tgl_lahir:  <input type="text" name="tgllahir" size="25"maxlength="50">
      Jenis Kelamin:
      <input type="radio" name="jeniskel" value="laki-laki">laki -laki
      <input type="radio" name="jeniskel" value="Perempuan">Perempuan
      pendidikan:
      <option value="S1">S1

      <p>
      <input type="submit" value="kirim"><input type="reset"value="Batal">
</form>
</body>
</html>








      
        


        







